[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sasit622", email = "sasit622@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "groq>=1.6.0",
    "python-dotenv>=1.2.3",
    "requests",
    "streamlit",
    "uvicorn>=0.52.4",
]

[project.scripts]
fastapi-project = "fastapi_project:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
